### ISSUE TITLE
"Bad request" when trying to delete room

### ISSUE THREAD

**Issue by GnaXi** [Awesome-Technologies/synapse-admin#21] opened 2020-03-15 15:31 UTC
When I try to delete a room it tries to send the request and spits out the error "Bad Request" shortly after. I can also see a "checkError400" in the console.

**Comment by awesome-michael** [comment] 2020-03-17 09:56
Propably some kind of duplicate of #17. Synapse does not support room deletion yet.

**Closed** 2020-03-30 16:46 UTC
