### ISSUE TITLE
Users list not working and showing Bad request

### ISSUE THREAD

**Issue by vranki** [Awesome-Technologies/synapse-admin#136] opened 2021-04-25 18:24 UTC
Looking at users list just shows red "Bad request" dialog and no users. Other pages seem to work fine.

Tested with docker version against up to date Synapse.

**Comment by gh0st68** [comment] 2021-04-25 18:33
I am having the same issue. (User list not working)

I have two matrix servers running.

One running {"server_version":"1.25.0","python_version":"3.8.5"}    WORKS
One running {"server_version":"1.32.2","python_version":"3.8.5"} DOES NOT WORK

I am guessing it's an issue with the latest Matrix Synapse Server VER?

Was able to manage users with Matrix-Synapse Admin GUI as a workaround.

**Comment by Fail-Unsafe** [comment] 2021-04-25 18:51
[There was a change concerning the API](https://github.com/matrix-org/synapse/releases/tag/v1.32.0rc1)

> This release removes the deprecated GET /_synapse/admin/v1/users/<user_id> admin API. Please use the v2 API instead, which has improved capabilities.

**Comment by gh0st68** [comment] 2021-04-25 19:06
I used the latest ver the pre-made docker one. Maybe that's just not updated yet?

**Comment by AAGaming00** [comment] 2021-04-25 19:35
Seems like `order_by=id` was changed to `order_by=name`?

**Comment by SiriusGale** [comment] 2021-04-26 15:17
Same problem
Synapse-Admin (0.7.2-6-gf8331a4) don't work well with newest Synapse Matrix

**Comment by dklimpel** [comment] 2021-04-27 11:02
PR #133 fixes it.


> Seems like `order_by=id` was changed to `order_by=name`

It was not changed. `order_by` is new. But synapse-admin set this by default with values which are not allowed.

**Comment by dklimpel** [comment] 2021-04-27 11:04
Duplicate of #132

**Comment by ThierryBegin** [comment] 2021-05-05 19:42
verified latest docker release and the problem still persist unfortunately

**Closed** 2021-05-06 14:03 UTC
