### ISSUE TITLE
Users order_by=id is not supported

### ISSUE THREAD

**Issue by waclaw66** [Awesome-Technologies/synapse-admin#132] opened 2021-04-21 14:57 UTC
Querying users `/_synapse/admin/v2/users?deactivated=false&dir=f&from=0&guests=true&limit=10&order_by=id` fails with
```
{"errcode":"M_UNKNOWN","error":"Query parameter b'order_by' must be one of ['name', 'displayname', 'is_guest', 'admin', 'deactivated', 'user_type', 'avatar_url', 'shadow_banned']"}
```
because `order_by` value `id` is not supported since Synapse 1.32.x

https://github.com/matrix-org/synapse/blob/master/docs/admin_api/user_admin_api.rst

**Comment by dklimpel** [comment] 2021-04-27 11:04
Duplicate of #136

**Comment by chagai95** [comment] 2021-05-01 14:38
same problem

![image](https://user-images.githubusercontent.com/31655082/116785766-974d2400-aa9b-11eb-8baf-e1bc2f9be7d4.png)

**Comment by maltalef101** [comment] 2021-05-01 22:10
same issue here
![image](https://user-images.githubusercontent.com/64824522/116796158-d174f080-aab0-11eb-88ea-779b58d208f9.png)

**Closed** 2021-05-04 14:21 UTC
Labels: duplicate
