### ISSUE TITLE
Yarn build error

### ISSUE THREAD

**Issue by NablaMetal** [Awesome-Technologies/synapse-admin#516] opened 2024-04-24 07:12 UTC
Hello,
Today the regular update process of my docker containers threw an error when building the synapse-admin container on the yarn build stage (see log).
My compose file is pretty straightforward:
```

  synapse-admin:
    container_name: synapse-admin
    hostname: synapse-admin
    build:
       context: https://github.com/Awesome-Technologies/synapse-admin.git
       args:
         - NODE_OPTIONS="--max_old_space_size=1024"
         # see #266, PUBLIC_URL must be without surrounding quotation marks
         - PUBLIC_URL=/synapse-admin
         - REACT_APP_SERVER=https://matrix.mywebsite.com
    restart: unless-stopped
    networks:
      - server_network
```
Log:
```
 => [synapse-admin internal] load metadata for docker.io/library/nginx:stable-alpine                                                                                                       0.4s
 => [synapse-admin internal] load metadata for docker.io/library/node:lts                                                                                                                  0.4s
 => [synapse-admin builder 1/7] FROM docker.io/library/node:lts@sha256:f89f8614e61a6da72ba33709a19560b9090a270ee9a8448de400717a5c63c644                                                    0.0s
 => CACHED [synapse-admin stage-1 1/3] FROM docker.io/library/nginx:stable-alpine@sha256:ca16009a8c25f52193506d4c90c98efbad4b6cbe73372e2a27972f05c5e02f15                                  0.0s
 => CACHED [synapse-admin builder 2/7] WORKDIR /src                                                                                                                                        0.0s
 => CACHED [synapse-admin builder 3/7] COPY .yarn .yarn                                                                                                                                    0.0s
 => CACHED [synapse-admin builder 4/7] COPY package.json .yarnrc.yml yarn.lock ./                                                                                                          0.0s
 => CACHED [synapse-admin builder 5/7] RUN yarn config set enableTelemetry 0 && yarn install --immutable --network-timeout=300000                                                          0.0s
 => CACHED [synapse-admin builder 6/7] COPY . /src                                                                                                                                         0.0s
=> ERROR [synapse-admin builder 7/7] RUN yarn build                                                                                                                                       2.4s
------
 > [synapse-admin builder 7/7] RUN yarn build:
2.206 error during build:
2.206 Error: Command failed: git describe --tags
2.206 fatal: not a git repository (or any of the parent directories): .git
2.206
2.206     at genericNodeError (node:internal/errors:984:15)
2.206     at wrappedFn (node:internal/errors:538:14)
2.206     at ChildProcess.exithandler (node:child_process:422:12)
2.206     at ChildProcess.emit (node:events:518:28)
2.206     at maybeClose (node:internal/child_process:1105:16)
2.206     at Socket.<anonymous> (node:internal/child_process:457:11)
2.206     at Socket.emit (node:events:518:28)
2.206     at Pipe.<anonymous> (node:net:337:12)
------
failed to solve: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1
```
My server is a physical host (no VM) running latest Ubuntu 64bit with descent hardware.

**Comment by awesome-manuel** [comment] 2024-04-24 07:54
Duplicate of #513

**Closed by awesome-manuel** 2024-04-24 07:54 UTC
Labels: duplicate
