### ISSUE TITLE
Server Communications Error

### ISSUE THREAD

**Issue by kmadaras** [Awesome-Technologies/synapse-admin#74] opened 2020-10-14 16:27 UTC
Hello,

Seems that no matter what I do in the project I get an error that says "Server Communications Error".  I don't have any sort of strange setup.  Everything is dockerized.  My Matrix/Synapse works fine.  Can you tell me where to look to troubleshoot as to why this may be happening?  Just FYI, I used the Ansible installer.  https://github.com/spantaleev/matrix-docker-ansible-deploy.

Thanks!

**Comment by awesome-michael** [comment] 2020-10-22 19:11
Does the reverse proxy correctly route /_synapse as well? The admin api uses _synapse instead of _matrix which is for the client api.

**Comment by awesome-manuel** [comment] 2020-11-12 14:07
Duplicate of #65 #75 #76

**Closed by awesome-manuel** 2020-11-12 14:07 UTC
