### ISSUE TITLE
Bulk remove rooms and media of selected user

### ISSUE THREAD

**Issue by wvffle** [Awesome-Technologies/synapse-admin#169] opened 2021-07-23 10:36 UTC
I'm trying to cleanup after mx-puppet-discord bridge as it does not leave the rooms that it unbridges nor does it remove the users. I could bulk delete the users, though I can't bulk delete the rooms in which the main puppet user is.

**Comment by JuniorJPDJ** [comment] 2021-07-23 12:26
probably duplicate of #121

**Closed** 2021-07-23 12:53 UTC
