### ISSUE TITLE
Wrong paths in index.html when using reverse proxy

### ISSUE THREAD

**Issue by kroonstaar** [Awesome-Technologies/synapse-admin#517] opened 2024-04-24 09:48 UTC
Since yesterday's commit (`f4ea63c`) the index.html is broken when served on a different path than `/` (using the provided traefik example). 

The `/src/index.jsx` (`/assets/index-XXXXX.js` after building) is referenced using an absolute path instead of being relative, like other files, e.g. the favicon and the manifest.

**Comment by krassle** [comment] 2024-04-24 12:56
Same here after `0.10.0` upgrade (docker with [mdad](https://github.com/spantaleev/matrix-docker-ansible-deploy)). A spinning circle is shown on the logging screen trying to load `/assets/***.js` instead of `/synapse-admin/assets/***`.

**Comment by Keeberos** [comment] 2024-04-24 13:12
I confirm that this is exactly what happens when upgrading to `0.10.0`

**Comment by awesome-manuel** [comment] 2024-04-24 13:21
Duplicate of #512

**Comment by kroonstaar** [comment] 2024-04-24 13:46
Noted. Could you add an option to change the base path via docker build arguments to the Dockerfile (i.e. `yarn build --base=$BASE_PATH`) as we had with homeserver restrictions before?

**Closed** 2024-04-24 15:03 UTC
Labels: duplicate
